name: Build Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      # 直接在 build.yml 文件里运行打包命令
      - name: Build Electron App for macOS (arm64)
        run: |
          cd src
          target=darwin npx electron-builder build --macos --arm64

      - name: Build Electron App for macOS (x64)
        run: |
          cd src
          target=darwin npx electron-builder build --macos --x64

      - name: Build Electron App for Windows (x64)
        run: |
          cd src
          target=win32 npx electron-builder build --win --x64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-build
          path: dist/
